### ISSUE TITLE
webpack 2.x not work at all

### ISSUE THREAD

**Issue by Delagen** [webpack/source-map-loader#15]
Emit error for `only path with file:// can be executed in node.`

**Comment by arnoudius** [comment]
I was able to get it to work in webpack 2.2.0-rc3, using this config:

module: {

    rules: [

      {
        enforce: 'pre',
        test: /\.js?$/,
        loader: 'source-map-loader'
      },

      {
            // other loader config
      }

       // other loaders etc

},
