### ISSUE TITLE
[Q&A] Why use loader instead of SourcemapDevToolPlugin?

### ISSUE THREAD

**Issue by Luchillo** [webpack/source-map-loader#17]
If there's a [SourceMapDevToolPlugin](https://webpack.github.io/docs/list-of-plugins.html#sourcemapdevtoolplugin) plugin that allows to specify ignores to the source map generation process, why use the loader at all?

**Comment by jsg2021** [comment]
That plugin is for generating sourcemaps from your code. This loader adds sourcemaps from libraries already complied. (from node_modules or your module root(s))

**Comment by Luchillo** [comment]
Ohh i see, thanks.

**Comment by philipstanislaus** [comment]
Could we add this (or an even longer) explanation to the readme? It is still a bit unclear to me whether I need this loader. Would help a lot if you could elaborate. Thanks  👍
